[package]
name = "cfg"
version = "0.9.0"
edition = "2021"

authors = [ "Piotr Czarnecki <pioczarn@gmail.com>" ]
description = "Library for manipulating context-free grammars."
keywords = ["grammar", "parsing", "language"]
documentation = "https://docs.rs/cfg/latest/cfg/"
homepage = "https://github.com/pczarn/cfg"
repository = "https://github.com/pczarn/cfg"
license = "MIT/Apache-2.0"

[lib]
name = "cfg"

[dependencies]
bit-matrix = "0.8"
bit-vec = "0.7"
cfg-symbol = { path = "../cfg-symbol/" }
cfg-grammar = { path = "../cfg-grammar/" }
cfg-classify = { path = "../cfg-classify/", optional = true }
cfg-generate = { path = "../cfg-generate/", optional = true }
cfg-earley = { path = "../cfg-earley/", optional = true }
cfg-predict = { path = "../cfg-predict/", optional = true }
cfg-sequence = { path = "../cfg-sequence/", optional = true }

rand = { version = "0.8", optional = true, features = ["small_rng"] }

# # serialize
# miniserde = { version = "0.1", optional = true }

[features]
default = ["cfg-classify", "cfg-generate", "cfg-earley", "cfg-predict", "cfg-generate", "cfg-sequence"]
serialize = ["cfg-grammar/serialize"]
ll = ["cfg-classify/cfg-predict"]
weighted-generation = ["cfg-generate/weighted", "cfg-generate", "rand"]
