[package]
name = "cfg-earley"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-symbol = { path = "../cfg-symbol/" }
cfg-classify = { path = "../cfg-classify/" }
cfg-grammar = { path = "../cfg-grammar/" }
cfg-sequence = { path = "../cfg-sequence/" }
bit-matrix = "0.8"
