[package]
name = "cfg-classify"
version = "0.0.1"
edition = "2021"

[dependencies]
cfg-grammar = { version = "0.0.1", path = "../cfg-grammar/" }
cfg-symbol = { version = "0.0.1", path = "../cfg-symbol/" }
cfg-predict = { version = "0.0.1", path = "../cfg-predict/", optional = true }
bit-matrix = "0.8"
bit-vec = "0.7"
