[package]
name = "cfg-classify"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-grammar = { path = "../cfg-grammar/" }
cfg-symbol = { path = "../cfg-symbol/" }
cfg-predict = { path = "../cfg-predict/", optional = true }
bit-matrix = "0.8"
bit-vec = "0.7"
